import Head from "next/head"
import Link from "next/link"
import styles from "../styles/Home.module.css"
import { useFavs } from "../context/FavsContext"
import BackButton from "../components/BackButton"

export default function Favs() {
  const { favorites: results } = useFavs()

  return (
    <div className={styles.container}>
      <Head>
        <title>Rick and Morty App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <BackButton />
        <ul className={styles.grid}>
          {!results.length && "No favs"}
          {results &&
            results.map((result) => {
              const { id, name, image } = result

              return (
                <Link
                  href={`/character/${id}`}
                  key={id}
                  className={styles.card}
                >
                  <a>
                    <img src={image} alt={`${name} Thumbnail`} />
                    <h3>{name}</h3>
                  </a>
                </Link>
              )
            })}
        </ul>
      </main>
    </div>
  )
}
