import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"

const api = "https://rickandmortyapi.com/api/character/"

export async function getServerSideProps() {
  const res = await fetch(api)
  const data = await res.json()
  return {
    props: {
      data,
    },
  }
}

export default function Home({ data }) {
  const { results = [] } = data
  console.log(results)
  return (
    <div className={styles.container}>
      <Head>
        <title>Rick and Morty App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Rick and Morty</h1>

        <p className={styles.description}>Wubba Lubba Dub Dub </p>
        <ul className="grid">
          {results.map((result) => {
            const { id, name, image } = result

            return (
              <li key={id} className="card">
                <img src={image} alt={`${name} Thumbnail`} />

                <a href="#">
                  <h3>{name}</h3>
                </a>
              </li>
            )
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
