import { useEffect } from "react"
import Head from "next/head"
import { useRouter } from "next/router"
import Link from "next/link"
import { useAuth } from "../context/AuthContext"
import styles from "../styles/Home.module.css"

export default function Home() {
  const { user } = useAuth()
  const router = useRouter()

  useEffect(() => {
    user && router.push("/list")
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Rick and Morty App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Rick and Morty</h1>
        <div style={{ display: "flex", margin: "2rem 0", gap: "1rem" }}>
          <button className={styles.button}>
            <Link href="/signup">
              <a>Sign Up</a>
            </Link>
          </button>
          <button className={styles.button}>
            <Link href="/login">
              <a>Log In</a>
            </Link>
          </button>
        </div>
      </main>
    </div>
  )
}
