import { useRouter } from "next/router"
import { useState } from "react"
import styles from "../styles/Home.module.css"
import Head from "next/head"
import { useAuth } from "../context/AuthContext"

const Login = () => {
  const router = useRouter()
  const { login } = useAuth()
  const [data, setData] = useState({
    email: "",
    password: "",
  })

  const handleLogin = async (e) => {
    e.preventDefault()

    try {
      await login(data.email, data.password)
      router.push("/list")
    } catch (err) {
      console.log(err)
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Rick and Morty App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Log In</h1>
        <form onSubmit={handleLogin}>
          <div>
            <p>Email</p>
            <input
              onChange={(e) =>
                setData({
                  ...data,
                  email: e.target.value,
                })
              }
              value={data.email}
              className={styles.input}
              required
              type="email"
              placeholder="Email"
            />
          </div>

          <div>
            <p>Password</p>
            <input
              onChange={(e) =>
                setData({
                  ...data,
                  password: e.target.value,
                })
              }
              value={data.password}
              required
              className={styles.input}
              type="password"
              placeholder="Password"
            />
          </div>
          <button className={styles.button} type="submit">
            Login
          </button>
        </form>
      </main>
    </div>
  )
}

export default Login
